### ISSUE TITLE
Inaccurate GPS Positions

### ISSUE THREAD

**Issue by ndjangula** [prey/prey-bash-client#360]
I left my laptop in "stolen" mode, just to test how well Prey worked.  However, the GPS position reports are incredibly inaccurate, showing my laptop is nearly 5 miles away from where it actually is.  About 10  reports have all turned up with the same location.  I've had zero issues my hot-spot showing wrong locations before, and my laptop shows the correct location if I use Google maps.  Why would Prey be kicking out a wrong location?  This makes me very uncomfortable with purchasing a pro plan, as it would be completely useless.

Thanks for your help!

```
 - Nate
```

**Comment by paleo13** [comment]
I think I'm having the same issue.

I've installed version 1.4.2 on a Linux (Ubuntu 14.04 LTS, KDE version 4 desktop) and Windows 7 computer. Prey works on Windows and not on my Linux system. These a are both running on the same network with the same login credentials.

The issue seems to be that on the linux system the GPS coordinates are rounded, this in turn leads to a loss of precision that seems like its giving the wrong coordinates.

My prey account is registered to jeffrey.hanson@uqconnect.edu.au. My windows computer is named CBCS-*********, and linux system is local****.

Please let me know if there is any other information I can provide.

**Comment by TerraD** [comment]
Up to my knowledge positioning based on WiFi (or GSM) **may** work in cities (=places with dense location of antennas) but will fail in rural areas. Moving a device triangulated this way only a few meters (e.g. to the opposite side of a house) may result in a location many hundred meters away.

Only GPS based systems will return an exact location (provided they area able to lock on enough satellites (which can not be guaranteed indoors)...

**Comment by paleo13** [comment]
@TerraD I think I understand what you're saying, but I don't see why this would also result in rounded GPS coordinates. Wouldn't this result in GPS coordinates of equal precision (ie. to same number of decimal points), but of different accuracy (ie. how far away the GPS estimate is away from the true GPS coordinate)?

For reference, I've attached screenshots of the activity logs from my Windows and Linux system from preyproject.com. 

Windows system:

![image](https://cloud.githubusercontent.com/assets/3610005/11487315/f33b1e20-9809-11e5-8845-c3dc09949b38.png)

Linux system:

![image](https://cloud.githubusercontent.com/assets/3610005/11487332/13a6af8a-980a-11e5-8f40-7807004e533b.png)

Thanks
